config/routes.rb
Rails.application.routes.draw do

root to: 'jobs#index'
devise_for :users
resources :jobs
resources :skills
resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  has_many :skills
  belongs_to :user
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :job
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :jobs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :move_to_index, except: :index

  def index
    @jobs = Job.all
  end

  def new
    @job = Job.new
  end

  def create
    Job.create(name: job_params[:name], life: job_params[:life], power: job_params[:power], skill: job_params[:skill], user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

  private
  def job_params
    params.require(:job).permit(:name, :life, :power, :skill)
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  def show
   @skills = Skill.where(job_id: params[:id])
   @job = Job.find(params[:id])
  end

  def destroy
    skill = Skill.find(params[:id])
    skill.destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/jobs/create.html.erb
<h1>登録完了！</h1>
<%= link_to "ジョブ一覧へ", jobs_path %>

app/views/jobs/index.html.erb
<h1>ジョブリスト一覧</h1>
<% if user_signed_in? %>
  <%= link_to "登録画面へ", new_job_path %> 
  <% @jobs.each do |job| %>
    <p><%= job.name %>：<%= job.skill %>:<%= job.user.nickname.present? ? "プレイヤー:#{job.user.nickname}" : "No.#{job.user.id}"%></p>  
  <% end %>
<% else %>
    <p>ログインしてください</p>
<% end %> 

app/views/jobs/new.html.erb
<p>新ジョブ追加</p>
<%= form_with model: @job, local: true do |f|%>
  <p>ジョブ名:<%= f.text_field :name %></p>
  <p>スキル:<%= f.text_field :skill %></p>
  <p>HP:<%= f.text_field :life %></p>
  <p>戦闘力:<%= f.text_field :power %></p>
  <%= f.submit "登録" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeviseSample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <% if user_signed_in? %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
      <%= link_to "トップ", jobs_path %>
      <%= link_to '投稿画面へ', new_job_path %>
      <%= link_to 'マイページへ', user_path(current_user.id) %>
    <% else %>
      <%= link_to "ログイン", new_user_session_path %>
      <%= link_to "新規登録", new_user_registration_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/skills/destroy.html.erb
<h1>削除完了</h1>
<%= link_to "一覧画面へ", skill_path %>

app/views/skills/show.html.erb
<%= link_to "ジョブ一覧へ", jobs_path %>
<h1>スキル一覧</h1>
  <% @skills.each do |skill| %>
    <p><%= skill.name %>：<%= skill.effect %></p>
    <p><%= "#{@job.name}は#{skill.power}を与えた" %></p>
    <!--<%= link_to "削除", skill_path(skill), method: :delete, data: {confirm: "削除しますか?"} %>-->
  <% end %>
  <%= link_to "戻る←", user_path(current_user.id)%>

app/views/users/show.html.erb
<% @user.jobs.each do |job| %>
  <p><%= job.name %>：<%= job.skill %></p>
  <%= link_to "詳細", skill_path(job) %>
<% end %>